# Generated by Django 4.2.3 on 2023-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_Id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, db_column='Customer_Name', max_length=255, null=True)),
                ('customer_address', models.CharField(blank=True, db_column='Customer_Address', max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, db_column='Customer_Phone', max_length=15, null=True)),
                ('customer_email', models.CharField(blank=True, db_column='Customer_Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='Order_Id', primary_key=True, serialize=False)),
                ('per_kg_price', models.DecimalField(blank=True, db_column='Per_Kg_Price', decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('subtotal', models.DecimalField(blank=True, db_column='Subtotal', decimal_places=2, max_digits=10, null=True)),
                ('order_date', models.DateField(blank=True, db_column='Order_Date', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='Product_Id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, db_column='Product_Name', max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, db_column='Product_Description', null=True)),
                ('product_quantity', models.IntegerField(blank=True, db_column='Product_Quantity', null=True)),
                ('product_price', models.DecimalField(blank=True, db_column='Product_Price', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('category_id', models.AutoField(db_column='Category_Id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, db_column='Category_Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
            ],
            options={
                'db_table': 'sign_up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(db_column='Supplier_Id', primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, db_column='Supplier_Name', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_number', max_length=15, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
    ]
