# Generated by Django 4.2.3 on 2023-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='Cart_Id', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(blank=True, db_column='Total_Amount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
