# Generated by Django 4.2.7 on 2024-04-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_invoice_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('expense_for', models.CharField(blank=True, db_column='Expense_For', max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'expense',
                'managed': False,
            },
        ),
    ]
